version: '2'
services:
  dashboard:
    image: fastscore/dashboard:1.6.1
    networks:
      - fastscore_net
    stdin_open: true
    ports:
      - "8000:8000"
    tty: true
    environment:
      CONNECT_PREFIX: https://connect:8001
      STRICT_SSL: "false"
    depends_on:
      - connect

  connect:
    image: fastscore/connect:1.6.1
    networks:
      - fastscore_net
    stdin_open: true
    tty: true
    expose:
      - "8001"
    ports:
      - "8001:8001"
    depends_on:
      - database

  engine-1:
    image: fastscore/engine-x:1.6.1
    networks:
      - fastscore_net
    stdin_open: true
    tty: true
    ports:
      - "8003:8003"
    volumes:
      - ./data-1:/root/data
    environment:
        CONNECT_PREFIX: https://connect:8001
    depends_on:
      - connect

  database:
    image: fastscore/model-manage-mysql:1.6.1
    networks:
      - fastscore_net
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
 
  model-manage:
    image: fastscore/model-manage:1.6.1
    networks:
      - fastscore_net
    stdin_open: true
    tty: true
    ports:
      - "8002:8002"
    depends_on:
      - connect
      - database
    environment:
      CONNECT_PREFIX: https://connect:8001

networks:
  fastscore_net:
    driver: bridge

volumes:
  db:
    external: true
